function [ st_sujet ] = tous_les_chemins_sujet( nom_sujet,rep_global )

if strcmp(nom_sujet,'golf_014_AD')
    nom_dossier_sujet='2016_09_14_golf_014_AD';
    nom_dossier_EOS='DeAl_M_1959';
    nom_fichier_trackman='golf_014_AD_trackman.xlsx';
    nom_fichier_excel_verif='golf_014_AD_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mouvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique01.c3d';
    nom_dossier_bodyscan='BodyScan';
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_015_JGC')
    nom_dossier_sujet='2016_09_15_golf_015_JGC';
    nom_dossier_EOS='ChJe_M_1941';
    nom_fichier_trackman='golf_015_JGC_trackman.xlsx';
    nom_fichier_excel_verif='golf_015_JGC_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mouvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique02.c3d';
    nom_dossier_bodyscan='BodyScan';
    nom_dossier_marche=[];
elseif strcmp(nom_sujet,'golf_016_JK')
    nom_dossier_sujet='2016_09_16_golf_016_JK';
    nom_dossier_EOS='KeJo_M_1954';
    nom_fichier_trackman='golf_016_JK_trackman.xlsx';
    nom_fichier_excel_verif='golf_016_JK_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mouvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique03.c3d';
    nom_dossier_bodyscan='BodyScan';
elseif strcmp(nom_sujet,'golf_017_AR')
    nom_dossier_sujet='2016_09_16_golf_017_AR';
    nom_dossier_EOS='RoAl_M_1950';
    nom_fichier_trackman='golf_017_AR_trackman.xlsx';
    nom_fichier_excel_verif='golf_017_AR_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mouvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique01.c3d';
    nom_dossier_bodyscan='BodyScan';
    nom_dossier_marche=[];
elseif strcmp(nom_sujet,'golf_018_MC')
    nom_dossier_sujet='2016_09_21_golf_018_MC';
    nom_dossier_EOS='CrMi_M_1979';
    nom_fichier_trackman='golf_018_MC_trackman.xlsx';
    nom_fichier_excel_verif='golf_018_MC_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6=[];
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mouvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique01.c3d';
    nom_dossier_bodyscan='BodyScan';
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_019_PS')
    nom_dossier_sujet='2016_11_21_golf_019_PS';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_019_PS_trackman.xlsx';
    nom_fichier_excel_verif='golf_019_PS_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mouvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statref_01.c3d';
    nom_dossier_bodyscan='BodyScan';
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_020_OR')
    nom_dossier_sujet='2016_11_21_golf_020_OR';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_020_OR_trackman.xlsx';
    nom_fichier_excel_verif='golf_020_OR_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statref 5.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_021_AMM')
    nom_dossier_sujet='2016_11_24_golf_021_AMM';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_021_AMM_trackman.xlsx';
    nom_fichier_excel_verif='golf_021_AMM_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique04.c3d';
    nom_dossier_bodyscan='BodyScan';
    nom_dossier_marche=[];
elseif strcmp(nom_sujet,'golf_022_GB')
    nom_dossier_sujet='2016_12_08_golf_022_GB';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_022_GB_trackman.xlsx';
    nom_fichier_excel_verif='golf_022_GB_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique04.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_023_OR')
    nom_dossier_sujet='2017_01_04_golf_023_OR';
    nom_dossier_EOS='RoOl_M_1990';
    nom_fichier_trackman='golf_023_OR_trackman.xlsx';
    nom_fichier_excel_verif='golf_023_OR_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_fichier_statique_valide='statique03.c3d';
    nom_dossier_statique='statique';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_024_RSS')
    nom_dossier_sujet='2017_01_04_golf_024_RSS';
    nom_dossier_EOS='ScRo_M_1993';
    nom_fichier_trackman='golf_024_RSS_trackman.xlsx';
    nom_fichier_excel_verif='golf_024_RSS_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique02.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche=[];
elseif strcmp(nom_sujet,'golf_025_TP')
    nom_dossier_sujet='2017_01_09_golf_025_TP';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_025_TP_trackman.xlsx';
    nom_fichier_excel_verif='golf_025_TP_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique02.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_027_WM')
    nom_dossier_sujet='2017_01_13_golf_027_WM';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_027_WM_trackman.xlsx';
    nom_fichier_excel_verif='golf_027_WM_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique03.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_028_AM')
    nom_dossier_sujet='2017_01_20_golf_028_AM';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_028_AM_trackman.xlsx';
    nom_fichier_excel_verif='golf_028_AM_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV=[];
    nom_dossier_putting=[];
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique01.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_033_LL')
    nom_dossier_sujet='2017_02_17_golf_033_LL';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_033_LL_trackman.xlsx';
    nom_fichier_excel_verif='golf_033_LL_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique05.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
elseif strcmp(nom_sujet,'golf_034_JS')
    nom_dossier_sujet='2017_02_20_golf_034_JS';
    nom_dossier_EOS=[];
    nom_fichier_trackman='golf_034_JS_trackman.xlsx';
    nom_fichier_excel_verif='golf_034_JS_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting='coupputting';
    nom_dossier_mvtfct='mvtfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique01.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche='marche';
%  
elseif strcmp(nom_sujet,'golf_036_XP')
    nom_dossier_sujet='2017_03_13_golf_036_XP';
    nom_dossier_EOS='PoXa_M_1985';
    nom_fichier_trackman='Golf_036_XP_trackman.xlsx';
    nom_fichier_excel_verif='golf_036_XP_labellisation.xlsx';
    nom_dossier_driver='coupdriver';
    nom_dossier_fer6='coupfer6';
    nom_dossier_MCV='MCV';
    nom_dossier_putting=[];
    nom_dossier_mvtfct='Mouvfct';
    nom_dossier_statique='statique';
    nom_fichier_statique_valide='statique04.c3d';
    nom_dossier_bodyscan=[];
    nom_dossier_marche=nom_dossier_mvtfct;
    
end


    st_sujet.chemin_global_sujet=fullfile(rep_global,nom_dossier_sujet);
    st_sujet.chemin_fichier_excel_verif=fullfile(rep_global,nom_dossier_sujet,nom_fichier_excel_verif);
    st_sujet.chemin_fichier_trackman=fullfile(rep_global,nom_dossier_sujet,nom_fichier_trackman);
    st_sujet.chemin_dossier_EOS=fullfile(rep_global,nom_dossier_sujet,nom_dossier_EOS);
    st_sujet.chemin_fer6=fullfile(rep_global,nom_dossier_sujet,nom_dossier_fer6);
    st_sujet.chemin_driver=fullfile(rep_global,nom_dossier_sujet,nom_dossier_driver);
    st_sujet.chemin_MCV=fullfile(rep_global,nom_dossier_sujet,nom_dossier_MCV);
    st_sujet.chemin_mvt_fct=fullfile(rep_global,nom_dossier_sujet,nom_dossier_mvtfct);
    st_sujet.chemin_putting=fullfile(rep_global,nom_dossier_sujet,nom_dossier_putting);
    st_sujet.chemin_statique_valide=fullfile(rep_global,nom_dossier_sujet,nom_dossier_statique,nom_fichier_statique_valide);
    st_sujet.dossier_bodyscan=fullfile(rep_global,nom_dossier_sujet,nom_dossier_bodyscan);
    st_sujet.chemin_marche=fullfile(rep_global,nom_dossier_sujet,nom_dossier_marche);
end

