function t_Q = angle_tangent_ellipse_final(a,b,P,Q)
%2 Solution from mathematica solving :
% Solve[(P*a*Cos[t])/a^2 + (Q*b*Sin[t])/b^2 == 1, {t}]

if abs(P)<a && abs(Q)<b
    disp('Le points est dans l''ellipse');
    t_Q = nan;
else
t_Q(1) =atan2( (...
    a*b - (a*b^3*P^2)/(b^2*P^2 + a^2*Q^2) + (...
    b*P*sqrt(-a^2*Q^2*(a^2*b^2 - b^2*P^2 - a^2*Q^2)))/(...
    b^2*P^2 + a^2*Q^2))/(a*Q),...
    (a*b^2*P - sqrt(-a^4*b^2*Q^2 + a^2*b^2*P^2*Q^2 + a^4*Q^4))/(...
    b^2*P^2 +a^2*Q^2));


t_Q(2) =atan2( -((-a*b + (a*b^3*P^2)/(b^2*P^2 + a^2*Q^2) + (...
    b*P*sqrt(-a^4*b^2*Q^2 + a^2*b^2*P^2*Q^2 + a^4*Q^4))/(...
    b^2*P^2 + a^2*Q^2))/(a*Q)),...
    (a*b^2*P + sqrt(-a^4*b^2*Q^2 + a^2*b^2*P^2*Q^2 + a^4*Q^4))/(...
    b^2*P^2 + ...
    a^2*Q^2)) ;
    
end
end